### ISSUE TITLE
Build error - Node v12?

### ISSUE THREAD

**Issue by thorsby** [ulwanski/unix-dgram-socket#4]
Trying to install this module from NPM, I get a bunch of compile errors, eg.:
`../src/unix_dgram.cc:358:28: error: no matching function for call to ‘v8::Value::Int32Value()’`

`../src/unix_dgram.cc:429:63: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
`

My knowledge on Nan is limited, but it must be related to V8 deprecating a lot of API calls. 

I think the similar library [node-unix-dgram](https://github.com/bnoordhuis/node-unix-dgram) got most of it covered in this commit:
https://github.com/bnoordhuis/node-unix-dgram/commit/0ae2a61c822f34d686de02792a2630527bb1f135#diff-8e3ec9d4b59eaf953bbd7fe258cb5700

**Comment by redneb** [comment]
I've attempted to provide a fix for this in #5.

**Comment by ulwanski** [comment]
Pull request #5 was merged, and I apply some additional compatibility changes.
It works under v12.x and v14.x
